# Generated by Django 3.1.7 on 2021-03-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='preciocompra',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precioventa',
            field=models.IntegerField(),
        ),
    ]
