# Generated by Django 3.1.7 on 2021-03-14 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_categoria_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='id',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='id',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Producto.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Producto.marca'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marca',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
