# Generated by Django 3.1.7 on 2021-03-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0005_auto_20210314_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoriafk',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marcafk',
        ),
    ]
