# Generated by Django 3.1.7 on 2021-03-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0006_auto_20210314_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='codigo',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='marca',
            old_name='codigo',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='codigo',
            new_name='id',
        ),
    ]
