# Generated by Django 3.1.7 on 2021-03-14 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0008_auto_20210314_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Producto.categoria', verbose_name=models.CharField(max_length=75)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Producto.marca', verbose_name=models.CharField(max_length=75)),
        ),
    ]
