# Generated by Django 3.1.7 on 2021-03-14 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0010_auto_20210314_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.marca'),
        ),
    ]
