# Generated by Django 3.1.7 on 2021-03-14 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0012_auto_20210314_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='Marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.marca'),
        ),
    ]
